# Generated by Django 5.1 on 2024-08-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0001_initial'),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categoryes',
            },
        ),
        migrations.CreateModel(
            name='CategoryPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categori.category', verbose_name='Category')),
                ('nursery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name': 'Category Plant',
                'verbose_name_plural': 'Categoryes Plants',
            },
        ),
    ]
