# Generated by Django 5.1 on 2024-08-31 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nursery_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nurseryes'),
            preserve_default=False,
        ),
    ]
