# Generated by Django 5.1 on 2024-08-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('decription', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(upload_to='plant', verbose_name='Image')),
                ('nursery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventoryes',
            },
        ),
    ]
