# Generated by Django 5.1 on 2024-08-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plants'),
        ),
    ]
