# Generated by Django 5.1 on 2024-08-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_rename_decription_plant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='plant.plant', unique=True, verbose_name='Plants'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.ImageField(upload_to='plants/', verbose_name='Image'),
        ),
    ]
