# Generated by Django 5.1 on 2024-08-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_inventory_nursery_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='nursery_id',
            new_name='nursery',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='nursery_id',
            new_name='nursery',
        ),
    ]
