# Generated by Django 5.1 on 2024-08-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('nursery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
            ],
            options={
                'verbose_name': 'Aboutus',
                'verbose_name_plural': 'Aboutus',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('urls', models.TextField(blank=True, null=True, verbose_name='Urls')),
                ('img', models.ImageField(blank=True, null=True, upload_to='socialnetwork', verbose_name='Image')),
                ('nursery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
            ],
            options={
                'verbose_name': 'SocialNetwork',
                'verbose_name_plural': 'SocialNetworks',
            },
        ),
    ]
