# Generated by Django 5.1 on 2024-08-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Social Network', 'verbose_name_plural': 'Social Networks'},
        ),
    ]
