# Generated by Django 5.1 on 2024-08-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_socialnetwork_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='nursery_id',
            new_name='nursery',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='nursery_id',
            new_name='nursery',
        ),
    ]
