# Generated by Django 5.1 on 2024-08-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('nursery', '0001_initial'),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('category_plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categoryplant', verbose_name='CategoryPlant')),
                ('nursery_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
                ('plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='HigtLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250, verbose_name='Reason')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('category_plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categoryplant', verbose_name='CategoryPlant')),
                ('nursery_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
                ('plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name': 'HigtLight',
                'verbose_name_plural': 'HigtLights',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250, verbose_name='Reason')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('start_date', models.DateTimeField(verbose_name='Start')),
                ('End_date', models.DateTimeField(verbose_name='End')),
                ('category_plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categoryplant', verbose_name='CategoryPlant')),
                ('nursery_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery', verbose_name='Nursery')),
                ('plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
